#!/bin/bash

rally_test=$@
echo "---"
echo "Running $rally_test"

rally_results_cmd=`rally task start $rally_test | grep "rally task result"`
#echo "$rally_results_cmd"
if [[ $rally_results_cmd == *'rally task results'* ]]
then
    rally_task_id=`echo $rally_results_cmd | sed 's/rally task results//g' | sed 's/ //g'`
    echo "ID: $rally_task_id"
    rally_results_path="/tmp/results/$rally_task_id"
    echo "Results file: $rally_results_path"
    $rally_results_cmd > $rally_results_path;
else
    rally_results_path=$rally_task
    echo $rally_results_path
fi
#echo $rally_results_path
rally_extract_command="/usr/local/bin/rally-extract-results $rally_results_path"
echo "---"
echo "Running: $rally_extract_command"
$rally_extract_command
